apiVersion: v1
kind: Service
metadata:
  name: pgwrite
  labels:
    component: patroni-patroni
spec:
  type: NodePort
  selector:
    component: patroni-patroni
    patroni-role: master
  ports:
  - port: 5432
